### ISSUE TITLE
Write a loaddata script to load some initial data for development

### ISSUE THREAD

**Issue by tonythomas01** [Quarantine-Help/quarantine-help-api#12]
Steps: 
1. Django provides some techniques to provide initial data. Explore: https://docs.djangoproject.com/en/3.0/howto/initial-data/ 
2. We might need the following: a crisis object, a couple of participants both as HL and AF, and a couple of requests from AF participants.

**Comment by igarcez** [comment]
> couple of requests from HL participants
do you mean Affected participants here? @tonythomas01

**Comment by tonythomas01** [comment]
Oops. Yes. Only AF participants can make requests. Let me correct it out.

**Comment by tonythomas01** [comment]
I think we have some stuff now, Thanks! Closing for now.
